FROM nvidia/cuda:10.2-base-ubuntu18.04

LABEL maintainer="aleksanderhan@gmail.com"
LABEL version="1.0"
LABEL description="trader training Dockerfile"

ENV DEBIAN_FRONTEND=noninteractive
ENV GPU_PLATFORM=1

WORKDIR = /

RUN apt update && apt upgrade -y
RUN apt install -y software-properties-common
RUN add-apt-repository universe
RUN apt update
